services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: global-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - global-network
volumes:
  portainer_data:
networks:
  global-network:
    name: global-network