services:
  rabbitmq:
    image: rabbitmq:management
    container_name: global-rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - global-network
volumes:
  rabbitmq_data:
networks:
  global-network:
    name: global-network